name: flutter_clinica_medica
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2+1
  sqflite_common_ffi_web: ^0.4.2+3 # Use a versão sugerida pelo `pub`
  intl: ^0.20.2 # Verifique a versão mais recente no pub.dev
  flutter_localizations: # ADICIONE ESTA LINHA
    sdk: flutter         # E ESTA LINHA
  url_launcher: ^6.1.0 # Certifique-se desta linha e da indentação
  crypto: ^3.0.3 # Verifique a versão mais recente
  pointycastle: ^3.7.3 # Verifique a versão mais recente


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true